const express = require('express');
const bodyParser = require('body-parser');
const oracledb = require('oracledb');
const path = require('path');
const expressLayouts = require('express-ejs-layouts');
const session = require('express-session');
const bcrypt = require('bcryptjs');
const multer = require('multer');

const app = express();

const NEAR_EXPIRY_DAYS = 3;
const NEAR_EXPIRY_DISCOUNT_PERCENT = 20;
const ADMIN_CREDENTIALS = {
  username: 'admin',
  password: 'admin123',
  name: 'Admin'
};

// ---------------- MULTER ----------------
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, 'public/uploads/'),
  filename: (req, file, cb) => cb(null, Date.now() + path.extname(file.originalname))
});
const upload = multer({ storage });

// ---------------- ORACLE ----------------
oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
oracledb.autoCommit = false;

const dbConfig = {
  user: 'C##FARMER',
  password: 'farmer123',
  connectString: 'localhost/XE'
};

let pool;

async function initDb() {
  try {
    pool = await oracledb.createPool(dbConfig);
    await ensureSchema();
    console.log('DB Connected');
  } catch (err) {
    console.error('DB ERROR:', err);
  }
}
initDb();

async function ensureSchema() {
  let conn;
  try {
    conn = await pool.getConnection();

    const schemaSteps = [
      `ALTER TABLE product ADD (expiry_date DATE)`,
      `ALTER TABLE product ADD (manual_discount_percent NUMBER(5,2) DEFAULT 0 NOT NULL)`,
      `ALTER TABLE order_details ADD (original_price NUMBER(10,2))`,
      `ALTER TABLE order_details ADD (discount_percent NUMBER(5,2) DEFAULT 0 NOT NULL)`,
      `ALTER TABLE orders ADD (delivery_address VARCHAR2(255))`,
      `ALTER TABLE orders ADD (refund_percent NUMBER(5,2) DEFAULT 0 NOT NULL)`,
      `ALTER TABLE orders ADD (refund_amount NUMBER(10,2) DEFAULT 0 NOT NULL)`,
      `ALTER TABLE orders ADD (cancelled_at TIMESTAMP NULL)`,
      `ALTER TABLE orders ADD (cancel_reason VARCHAR2(255))`
    ];

    for (const sql of schemaSteps) {
      try {
        await conn.execute(sql);
      } catch (err) {
        if (!err || err.errorNum !== 1430) {
          throw err;
        }
      }
    }

    try {
      await conn.execute(`
        CREATE TABLE product_reviews (
          review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          order_id NUMBER NOT NULL REFERENCES orders(order_id),
          product_id NUMBER NOT NULL REFERENCES product(product_id),
          customer_id NUMBER NOT NULL REFERENCES customer(customer_id),
          rating NUMBER(2) NOT NULL CHECK (rating BETWEEN 1 AND 5),
          review_text VARCHAR2(1000),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT uq_product_review UNIQUE (order_id, product_id, customer_id)
        )
      `);
    } catch (err) {
      if (!err || err.errorNum !== 955) {
        throw err;
      }
    }

    await conn.execute(`
      UPDATE product
      SET expiry_date = NVL(expiry_date, TRUNC(SYSDATE) + 7)
      WHERE expiry_date IS NULL
    `);

    await conn.execute(`
      UPDATE product
      SET manual_discount_percent = NVL(manual_discount_percent, 0)
      WHERE manual_discount_percent IS NULL
    `);

    await conn.execute(`
      UPDATE order_details
      SET original_price = NVL(original_price, price),
          discount_percent = NVL(discount_percent, 0)
      WHERE original_price IS NULL
         OR discount_percent IS NULL
    `);

    await conn.execute(`
      UPDATE orders
      SET refund_percent = NVL(refund_percent, 0),
          refund_amount = NVL(refund_amount, 0)
      WHERE refund_percent IS NULL
         OR refund_amount IS NULL
    `);

    const plsqlObjects = [
      `
        CREATE OR REPLACE PACKAGE marketplace_pkg AS
          FUNCTION get_effective_discount(
            p_expiry_date IN DATE,
            p_manual_discount_percent IN NUMBER
          ) RETURN NUMBER;

          PROCEDURE add_farmer(
            p_name IN VARCHAR2,
            p_phone IN VARCHAR2,
            p_location IN VARCHAR2,
            p_bank IN VARCHAR2,
            p_password_hash IN VARCHAR2,
            p_farmer_id OUT NUMBER
          );

          PROCEDURE add_customer(
            p_name IN VARCHAR2,
            p_email IN VARCHAR2,
            p_phone IN VARCHAR2,
            p_address IN VARCHAR2,
            p_password_hash IN VARCHAR2,
            p_customer_id OUT NUMBER
          );

          PROCEDURE add_product(
            p_farmer_id IN NUMBER,
            p_product_name IN VARCHAR2,
            p_category IN VARCHAR2,
            p_price_per_kg IN NUMBER,
            p_available_quantity IN NUMBER,
            p_image_url IN VARCHAR2,
            p_expiry_date IN DATE,
            p_manual_discount_percent IN NUMBER,
            p_product_id OUT NUMBER
          );

          PROCEDURE update_product(
            p_product_id IN NUMBER,
            p_farmer_id IN NUMBER,
            p_product_name IN VARCHAR2,
            p_category IN VARCHAR2,
            p_price_per_kg IN NUMBER,
            p_available_quantity IN NUMBER,
            p_expiry_date IN DATE,
            p_manual_discount_percent IN NUMBER,
            p_image_url IN VARCHAR2
          );

          PROCEDURE delete_product_if_unused(
            p_product_id IN NUMBER,
            p_farmer_id IN NUMBER
          );

          PROCEDURE place_grouped_order_transaction(
            p_customer_id IN NUMBER,
            p_product_id IN NUMBER,
            p_quantity IN NUMBER,
            p_price IN NUMBER,
            p_original_price IN NUMBER,
            p_discount_percent IN NUMBER,
            p_payment_mode IN VARCHAR2,
            p_delivery_address IN VARCHAR2,
            p_order_id OUT NUMBER
          );

          PROCEDURE cancel_customer_order(
            p_order_id IN NUMBER,
            p_customer_id IN NUMBER,
            p_cancel_reason IN VARCHAR2,
            p_refund_percent OUT NUMBER,
            p_refund_amount OUT NUMBER
          );

          PROCEDURE save_product_review(
            p_order_id IN NUMBER,
            p_product_id IN NUMBER,
            p_customer_id IN NUMBER,
            p_rating IN NUMBER,
            p_review_text IN VARCHAR2
          );

          PROCEDURE update_farmer_order_status(
            p_order_id IN NUMBER,
            p_farmer_id IN NUMBER,
            p_status IN VARCHAR2
          );

          FUNCTION get_total_revenue RETURN NUMBER;
        END marketplace_pkg;
      `,
      `
        CREATE OR REPLACE PACKAGE BODY marketplace_pkg AS
          FUNCTION get_effective_discount(
            p_expiry_date IN DATE,
            p_manual_discount_percent IN NUMBER
          ) RETURN NUMBER IS
            v_near_expiry_discount NUMBER := 0;
          BEGIN
            IF p_expiry_date IS NOT NULL
               AND p_expiry_date >= TRUNC(SYSDATE)
               AND p_expiry_date <= TRUNC(SYSDATE) + ${NEAR_EXPIRY_DAYS} THEN
              v_near_expiry_discount := ${NEAR_EXPIRY_DISCOUNT_PERCENT};
            END IF;

            RETURN GREATEST(NVL(p_manual_discount_percent, 0), v_near_expiry_discount);
          END get_effective_discount;

          PROCEDURE add_farmer(
            p_name IN VARCHAR2,
            p_phone IN VARCHAR2,
            p_location IN VARCHAR2,
            p_bank IN VARCHAR2,
            p_password_hash IN VARCHAR2,
            p_farmer_id OUT NUMBER
          ) IS
          BEGIN
            INSERT INTO farmer (name, phone, location, bank_details, password_hash)
            VALUES (p_name, p_phone, p_location, p_bank, p_password_hash)
            RETURNING farmer_id INTO p_farmer_id;
          END add_farmer;

          PROCEDURE add_customer(
            p_name IN VARCHAR2,
            p_email IN VARCHAR2,
            p_phone IN VARCHAR2,
            p_address IN VARCHAR2,
            p_password_hash IN VARCHAR2,
            p_customer_id OUT NUMBER
          ) IS
          BEGIN
            INSERT INTO customer (name, email, phone, address, password_hash)
            VALUES (p_name, p_email, p_phone, p_address, p_password_hash)
            RETURNING customer_id INTO p_customer_id;
          END add_customer;

          PROCEDURE add_product(
            p_farmer_id IN NUMBER,
            p_product_name IN VARCHAR2,
            p_category IN VARCHAR2,
            p_price_per_kg IN NUMBER,
            p_available_quantity IN NUMBER,
            p_image_url IN VARCHAR2,
            p_expiry_date IN DATE,
            p_manual_discount_percent IN NUMBER,
            p_product_id OUT NUMBER
          ) IS
          BEGIN
            INSERT INTO product (
              farmer_id, product_name, category, price_per_kg, available_quantity, image_url, expiry_date, manual_discount_percent
            ) VALUES (
              p_farmer_id, p_product_name, p_category, p_price_per_kg, p_available_quantity, p_image_url, p_expiry_date, p_manual_discount_percent
            )
            RETURNING product_id INTO p_product_id;
          END add_product;

          PROCEDURE update_product(
            p_product_id IN NUMBER,
            p_farmer_id IN NUMBER,
            p_product_name IN VARCHAR2,
            p_category IN VARCHAR2,
            p_price_per_kg IN NUMBER,
            p_available_quantity IN NUMBER,
            p_expiry_date IN DATE,
            p_manual_discount_percent IN NUMBER,
            p_image_url IN VARCHAR2
          ) IS
            v_updated NUMBER;
          BEGIN
            UPDATE product
            SET product_name = p_product_name,
                category = p_category,
                price_per_kg = p_price_per_kg,
                available_quantity = p_available_quantity,
                expiry_date = p_expiry_date,
                manual_discount_percent = p_manual_discount_percent,
                image_url = p_image_url
            WHERE product_id = p_product_id
              AND farmer_id = p_farmer_id;

            v_updated := SQL%ROWCOUNT;
            IF v_updated = 0 THEN
              RAISE_APPLICATION_ERROR(-20004, 'Product not found.');
            END IF;
          END update_product;

          PROCEDURE delete_product_if_unused(
            p_product_id IN NUMBER,
            p_farmer_id IN NUMBER
          ) IS
            v_order_count NUMBER;
            v_deleted NUMBER;
          BEGIN
            SELECT COUNT(*)
            INTO v_order_count
            FROM order_details
            WHERE product_id = p_product_id;

            IF v_order_count > 0 THEN
              RAISE_APPLICATION_ERROR(-20005, 'Cannot delete a product that already has orders.');
            END IF;

            DELETE FROM product
            WHERE product_id = p_product_id
              AND farmer_id = p_farmer_id;

            v_deleted := SQL%ROWCOUNT;
            IF v_deleted = 0 THEN
              RAISE_APPLICATION_ERROR(-20004, 'Product not found.');
            END IF;
          END delete_product_if_unused;

          PROCEDURE place_grouped_order_transaction(
            p_customer_id IN NUMBER,
            p_product_id IN NUMBER,
            p_quantity IN NUMBER,
            p_price IN NUMBER,
            p_original_price IN NUMBER,
            p_discount_percent IN NUMBER,
            p_payment_mode IN VARCHAR2,
            p_delivery_address IN VARCHAR2,
            p_order_id OUT NUMBER
          ) IS
            v_total NUMBER(10,2);
            v_available_quantity NUMBER(10,2);
            v_expiry_date DATE;
          BEGIN
            SELECT available_quantity, expiry_date
            INTO v_available_quantity, v_expiry_date
            FROM product
            WHERE product_id = p_product_id
            FOR UPDATE;

            IF v_expiry_date < TRUNC(SYSDATE) THEN
              RAISE_APPLICATION_ERROR(-20006, 'Expired products cannot be ordered.');
            END IF;

            IF v_available_quantity < p_quantity THEN
              RAISE_APPLICATION_ERROR(-20007, 'Requested quantity exceeds stock.');
            END IF;

            v_total := p_price * p_quantity;

            INSERT INTO orders (customer_id, total_amount, order_status, delivery_address)
            VALUES (p_customer_id, v_total, 'Placed', p_delivery_address)
            RETURNING order_id INTO p_order_id;

            INSERT INTO order_details (order_id, product_id, quantity, price, original_price, discount_percent)
            VALUES (p_order_id, p_product_id, p_quantity, p_price, p_original_price, p_discount_percent);

            INSERT INTO payment (order_id, payment_mode, payment_status)
            VALUES (p_order_id, p_payment_mode, 'Success');
          END place_grouped_order_transaction;

          PROCEDURE cancel_customer_order(
            p_order_id IN NUMBER,
            p_customer_id IN NUMBER,
            p_cancel_reason IN VARCHAR2,
            p_refund_percent OUT NUMBER,
            p_refund_amount OUT NUMBER
          ) IS
            v_order_status orders.order_status%TYPE;
            v_total_amount orders.total_amount%TYPE;
          BEGIN
            SELECT order_status, total_amount
            INTO v_order_status, v_total_amount
            FROM orders
            WHERE order_id = p_order_id
              AND customer_id = p_customer_id
            FOR UPDATE;

            IF v_order_status NOT IN ('Placed', 'Packed', 'Shipped') THEN
              RAISE_APPLICATION_ERROR(-20008, 'This order can no longer be cancelled.');
            END IF;

            p_refund_percent := CASE v_order_status
              WHEN 'Placed' THEN 100
              WHEN 'Packed' THEN 75
              WHEN 'Shipped' THEN 50
              ELSE 0
            END;
            p_refund_amount := ROUND(v_total_amount * (p_refund_percent / 100), 2);

            FOR detail IN (
              SELECT product_id, quantity
              FROM order_details
              WHERE order_id = p_order_id
            ) LOOP
              UPDATE product
              SET available_quantity = available_quantity + detail.quantity
              WHERE product_id = detail.product_id;
            END LOOP;

            UPDATE orders
            SET order_status = 'Cancelled',
                refund_percent = p_refund_percent,
                refund_amount = p_refund_amount,
                cancelled_at = CURRENT_TIMESTAMP,
                cancel_reason = p_cancel_reason
            WHERE order_id = p_order_id;

            UPDATE payment
            SET payment_status = 'Refund ' || p_refund_percent || '% processed'
            WHERE order_id = p_order_id;
          END cancel_customer_order;

          PROCEDURE save_product_review(
            p_order_id IN NUMBER,
            p_product_id IN NUMBER,
            p_customer_id IN NUMBER,
            p_rating IN NUMBER,
            p_review_text IN VARCHAR2
          ) IS
            v_eligible_count NUMBER;
            v_existing_count NUMBER;
          BEGIN
            SELECT COUNT(*)
            INTO v_eligible_count
            FROM orders o
            JOIN order_details od ON od.order_id = o.order_id
            WHERE o.order_id = p_order_id
              AND od.product_id = p_product_id
              AND o.customer_id = p_customer_id
              AND o.order_status = 'Delivered';

            IF v_eligible_count = 0 THEN
              RAISE_APPLICATION_ERROR(-20009, 'Reviews are allowed only for delivered orders.');
            END IF;

            SELECT COUNT(*)
            INTO v_existing_count
            FROM product_reviews
            WHERE order_id = p_order_id
              AND product_id = p_product_id
              AND customer_id = p_customer_id;

            IF v_existing_count > 0 THEN
              UPDATE product_reviews
              SET rating = p_rating,
                  review_text = p_review_text,
                  created_at = CURRENT_TIMESTAMP
              WHERE order_id = p_order_id
                AND product_id = p_product_id
                AND customer_id = p_customer_id;
            ELSE
              INSERT INTO product_reviews (order_id, product_id, customer_id, rating, review_text)
              VALUES (p_order_id, p_product_id, p_customer_id, p_rating, p_review_text);
            END IF;
          END save_product_review;

          PROCEDURE update_farmer_order_status(
            p_order_id IN NUMBER,
            p_farmer_id IN NUMBER,
            p_status IN VARCHAR2
          ) IS
            v_order_count NUMBER;
            v_current_status orders.order_status%TYPE;
          BEGIN
            SELECT COUNT(*)
            INTO v_order_count
            FROM order_details od
            JOIN product p ON p.product_id = od.product_id
            WHERE od.order_id = p_order_id
              AND p.farmer_id = p_farmer_id;

            IF v_order_count = 0 THEN
              RAISE_APPLICATION_ERROR(-20010, 'Order not found for this farmer.');
            END IF;

            SELECT order_status
            INTO v_current_status
            FROM orders
            WHERE order_id = p_order_id
            FOR UPDATE;

            IF v_current_status = 'Cancelled' THEN
              RAISE_APPLICATION_ERROR(-20011, 'Cancelled orders cannot be updated.');
            END IF;

            UPDATE orders
            SET order_status = p_status
            WHERE order_id = p_order_id;
          END update_farmer_order_status;

          FUNCTION get_total_revenue RETURN NUMBER IS
            v_total NUMBER := 0;
          BEGIN
            SELECT NVL(SUM(o.total_amount), 0)
            INTO v_total
            FROM orders o
            JOIN payment p ON o.order_id = p.order_id
            WHERE p.payment_status = 'Success';

            RETURN v_total;
          EXCEPTION
            WHEN NO_DATA_FOUND THEN
              RETURN 0;
          END get_total_revenue;
        END marketplace_pkg;
      `,
      `
        CREATE OR REPLACE PROCEDURE add_farmer(
          p_name IN farmer.name%TYPE,
          p_phone IN farmer.phone%TYPE,
          p_location IN farmer.location%TYPE,
          p_bank IN farmer.bank_details%TYPE,
          p_password_hash IN farmer.password_hash%TYPE,
          p_farmer_id OUT farmer.farmer_id%TYPE
        )
        IS
        BEGIN
          marketplace_pkg.add_farmer(p_name, p_phone, p_location, p_bank, p_password_hash, p_farmer_id);
        END;
      `,
      `
        CREATE OR REPLACE PROCEDURE place_grouped_order_transaction (
          p_customer_id IN NUMBER,
          p_product_id IN NUMBER,
          p_quantity IN NUMBER,
          p_price IN NUMBER,
          p_original_price IN NUMBER,
          p_discount_percent IN NUMBER,
          p_payment_mode IN VARCHAR2,
          p_delivery_address IN VARCHAR2,
          p_order_id OUT NUMBER
        )
        IS
        BEGIN
          marketplace_pkg.place_grouped_order_transaction(
            p_customer_id, p_product_id, p_quantity, p_price, p_original_price, p_discount_percent,
            p_payment_mode, p_delivery_address, p_order_id
          );
        END;
      `,
      `
        CREATE OR REPLACE FUNCTION get_total_revenue
        RETURN NUMBER
        IS
        BEGIN
          RETURN marketplace_pkg.get_total_revenue();
        END;
      `,
      `
        CREATE OR REPLACE VIEW product_catalog_view AS
        SELECT
          p.product_id,
          p.farmer_id,
          f.name AS farmer_name,
          p.product_name,
          p.category,
          p.price_per_kg,
          p.available_quantity,
          p.image_url,
          p.expiry_date,
          NVL(p.manual_discount_percent, 0) AS manual_discount_percent,
          marketplace_pkg.get_effective_discount(p.expiry_date, p.manual_discount_percent) AS discount_percent,
          ROUND(
            p.price_per_kg * (
              1 - marketplace_pkg.get_effective_discount(p.expiry_date, p.manual_discount_percent) / 100
            ),
            2
          ) AS discounted_price_per_kg,
          CASE
            WHEN p.expiry_date IS NOT NULL THEN TRUNC(p.expiry_date) - TRUNC(SYSDATE)
            ELSE NULL
          END AS days_until_expiry,
          CASE
            WHEN p.expiry_date IS NOT NULL AND TRUNC(p.expiry_date) < TRUNC(SYSDATE) THEN 1
            ELSE 0
          END AS is_expired,
          CASE
            WHEN p.expiry_date IS NOT NULL
             AND TRUNC(p.expiry_date) >= TRUNC(SYSDATE)
             AND TRUNC(p.expiry_date) <= TRUNC(SYSDATE) + ${NEAR_EXPIRY_DAYS} THEN 1
            ELSE 0
          END AS is_near_expiry,
          NVL(rv.average_rating, 0) AS average_rating,
          NVL(rv.review_count, 0) AS review_count
        FROM product p
        JOIN farmer f ON f.farmer_id = p.farmer_id
        LEFT JOIN (
          SELECT product_id,
                 ROUND(AVG(rating), 1) AS average_rating,
                 COUNT(*) AS review_count
          FROM product_reviews
          GROUP BY product_id
        ) rv ON rv.product_id = p.product_id
      `,
      `
        CREATE OR REPLACE VIEW customer_order_view AS
        SELECT
          o.order_id,
          o.customer_id,
          o.order_date,
          o.order_status,
          o.delivery_address,
          o.refund_percent,
          o.refund_amount,
          o.cancelled_at,
          o.cancel_reason,
          od.product_id,
          od.quantity,
          od.price,
          od.original_price,
          od.discount_percent,
          p.product_name,
          p.image_url,
          f.name AS farmer_name,
          rv.rating AS customer_rating,
          rv.review_text,
          rv.created_at AS review_created_at
        FROM orders o
        JOIN order_details od ON od.order_id = o.order_id
        JOIN product p ON p.product_id = od.product_id
        JOIN farmer f ON f.farmer_id = p.farmer_id
        LEFT JOIN product_reviews rv
          ON rv.order_id = o.order_id
         AND rv.product_id = p.product_id
         AND rv.customer_id = o.customer_id
      `,
      `
        CREATE OR REPLACE VIEW farmer_order_view AS
        SELECT
          o.order_id,
          o.order_date,
          o.order_status,
          o.delivery_address,
          o.refund_percent,
          o.refund_amount,
          o.cancelled_at,
          o.cancel_reason,
          p.farmer_id,
          c.name AS customer_name,
          c.phone AS customer_phone,
          c.email AS customer_email,
          pmt.payment_mode,
          od.quantity,
          od.price,
          od.original_price,
          od.discount_percent,
          p.product_name
        FROM orders o
        JOIN order_details od ON od.order_id = o.order_id
        JOIN product p ON p.product_id = od.product_id
        JOIN customer c ON c.customer_id = o.customer_id
        JOIN payment pmt ON pmt.order_id = o.order_id
      `,
      `
        CREATE OR REPLACE VIEW admin_order_view AS
        SELECT
          o.order_id,
          o.order_date,
          o.order_status,
          o.delivery_address,
          o.refund_percent,
          o.refund_amount,
          o.cancelled_at,
          o.cancel_reason,
          c.name AS customer_name,
          pmt.payment_mode,
          od.quantity,
          od.price,
          od.original_price,
          od.discount_percent,
          p.product_name,
          f.name AS farmer_name
        FROM orders o
        JOIN customer c ON c.customer_id = o.customer_id
        JOIN payment pmt ON pmt.order_id = o.order_id
        JOIN order_details od ON od.order_id = o.order_id
        JOIN product p ON p.product_id = od.product_id
        JOIN farmer f ON f.farmer_id = p.farmer_id
      `,
      `
        CREATE OR REPLACE TRIGGER trg_prevent_negative_price
        BEFORE INSERT OR UPDATE ON product
        FOR EACH ROW
        BEGIN
          IF :NEW.price_per_kg <= 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Price per kg must be greater than zero.');
          END IF;
        END;
      `,
      `
        CREATE OR REPLACE TRIGGER trg_update_stock_after_order
        AFTER INSERT ON order_details
        FOR EACH ROW
        BEGIN
          UPDATE product
          SET available_quantity = available_quantity - :NEW.quantity
          WHERE product_id = :NEW.product_id;
        END;
      `
    ];

    for (const sql of plsqlObjects) {
      await conn.execute(sql);
    }

    await conn.commit();
  } finally {
    if (conn) await conn.close();
  }
}

// ---------------- MIDDLEWARE ----------------
app.use(expressLayouts);
app.set('layout', 'layout');
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));

app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'public')));

app.use(session({
  secret: 'secret_key',
  resave: false,
  saveUninitialized: false
}));

app.use((req, res, next) => {
  const cart = getSessionCart(req);
  res.locals.user = req.session.user || null;
  res.locals.userType = req.session.userType || null;
  res.locals.cartCount = cart.length;
  res.locals.currentPath = req.path;
  next();
});

// ---------------- HELPERS ----------------
async function runQuery(sql, binds = [], options = {}) {
  let conn;
  try {
    conn = await pool.getConnection();
    return await conn.execute(sql, binds, options);
  } finally {
    if (conn) await conn.close();
  }
}

function toLowerKeys(row) {
  const obj = {};
  for (const key in row) obj[key.toLowerCase()] = row[key];
  return obj;
}

function parseNumber(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : NaN;
}

function roundCurrency(value) {
  return Math.round(value * 100) / 100;
}

function getSessionCart(req) {
  if (!Array.isArray(req.session.cart)) {
    req.session.cart = [];
  }
  return req.session.cart;
}

function startOfDay(dateValue) {
  const date = new Date(dateValue);
  date.setHours(0, 0, 0, 0);
  return date;
}

function formatDateInput(dateValue) {
  if (!dateValue) return '';
  const date = new Date(dateValue);
  if (Number.isNaN(date.getTime())) return '';
  return date.toISOString().slice(0, 10);
}

function enrichProduct(product) {
  const originalPrice = Number(product.price_per_kg);
  const manualDiscountPercent = Number(product.manual_discount_percent || 0);
  const reviewCount = Number(product.review_count || 0);
  const averageRating = reviewCount ? Number(product.average_rating || 0) : 0;
  const expiryDate = product.expiry_date ? new Date(product.expiry_date) : null;
  const daysUntilExpiry = product.days_until_expiry !== undefined && product.days_until_expiry !== null
    ? Number(product.days_until_expiry)
    : (expiryDate && !Number.isNaN(expiryDate.getTime())
        ? Math.ceil((startOfDay(expiryDate) - startOfDay(new Date())) / (1000 * 60 * 60 * 24))
        : null);
  const isExpired = product.is_expired !== undefined
    ? Boolean(Number(product.is_expired))
    : daysUntilExpiry !== null && daysUntilExpiry < 0;
  const isNearExpiry = product.is_near_expiry !== undefined
    ? Boolean(Number(product.is_near_expiry))
    : daysUntilExpiry !== null && daysUntilExpiry >= 0 && daysUntilExpiry <= NEAR_EXPIRY_DAYS;
  const discountPercent = product.discount_percent !== undefined && product.discount_percent !== null
    ? Number(product.discount_percent)
    : Math.max(manualDiscountPercent, isNearExpiry ? NEAR_EXPIRY_DISCOUNT_PERCENT : 0);
  const discountedPrice = product.discounted_price_per_kg !== undefined && product.discounted_price_per_kg !== null
    ? Number(product.discounted_price_per_kg)
    : roundCurrency(originalPrice * (1 - discountPercent / 100));
  const nearExpiryDiscount = isNearExpiry ? NEAR_EXPIRY_DISCOUNT_PERCENT : 0;

  return {
    ...product,
    price_per_kg: originalPrice,
    original_price_per_kg: originalPrice,
    discounted_price_per_kg: discountedPrice,
    discount_percent: discountPercent,
    manual_discount_percent: manualDiscountPercent,
    review_count: reviewCount,
    average_rating: averageRating,
    near_expiry_discount_percent: nearExpiryDiscount,
    days_until_expiry: daysUntilExpiry,
    is_near_expiry: isNearExpiry,
    is_expired: isExpired,
    expiry_input_value: formatDateInput(expiryDate),
    expiry_display: expiryDate && !Number.isNaN(expiryDate.getTime())
      ? expiryDate.toLocaleDateString()
      : 'Not set'
  };
}

function buildInClause(values, offset = 1) {
  return values.map((_, index) => `:${index + offset}`).join(', ');
}

async function fetchProductsByIds(productIds, conn = null) {
  if (!productIds.length) {
    return [];
  }

  const sql = `
    SELECT *
    FROM product_catalog_view
    WHERE product_id IN (${buildInClause(productIds)})
  `;

  const result = conn
    ? await conn.execute(sql, productIds)
    : await runQuery(sql, productIds);

  return result.rows.map((row) => enrichProduct(toLowerKeys(row)));
}

async function buildCartState(req, conn = null) {
  const cart = getSessionCart(req);
  if (!cart.length) {
    return {
      items: [],
      groups: [],
      total: 0,
      totalOriginal: 0,
      savings: 0,
      hasIssues: false
    };
  }

  const productIds = [...new Set(cart.map((item) => Number(item.product_id)).filter(Boolean))];
  const products = await fetchProductsByIds(productIds, conn);
  const productMap = new Map(products.map((product) => [Number(product.product_id), product]));

  const items = [];
  for (const cartItem of cart) {
    const product = productMap.get(Number(cartItem.product_id));
    if (!product) {
      continue;
    }

    const quantity = parseNumber(cartItem.quantity);
    if (!quantity || quantity <= 0) {
      continue;
    }

    const subtotal = roundCurrency(quantity * product.discounted_price_per_kg);
    const originalSubtotal = roundCurrency(quantity * product.original_price_per_kg);

    items.push({
      ...product,
      quantity,
      subtotal,
      original_subtotal: originalSubtotal,
      savings: roundCurrency(originalSubtotal - subtotal),
      has_stock_issue: quantity > Number(product.available_quantity)
    });
  }

  const groupsMap = new Map();
  for (const item of items) {
    if (!groupsMap.has(item.farmer_id)) {
      groupsMap.set(item.farmer_id, {
        farmer_id: item.farmer_id,
        farmer_name: item.farmer_name,
        items: [],
        total: 0,
        totalOriginal: 0,
        savings: 0
      });
    }

    const group = groupsMap.get(item.farmer_id);
    group.items.push(item);
    group.total = roundCurrency(group.total + item.subtotal);
    group.totalOriginal = roundCurrency(group.totalOriginal + item.original_subtotal);
    group.savings = roundCurrency(group.savings + item.savings);
  }

  const groups = Array.from(groupsMap.values());
  return {
    items,
    groups,
    total: roundCurrency(items.reduce((sum, item) => sum + item.subtotal, 0)),
    totalOriginal: roundCurrency(items.reduce((sum, item) => sum + item.original_subtotal, 0)),
    savings: roundCurrency(items.reduce((sum, item) => sum + item.savings, 0)),
    hasIssues: items.some((item) => item.is_expired || item.has_stock_issue)
  };
}

function sanitizeCart(req) {
  const cart = getSessionCart(req)
    .map((item) => ({
      product_id: Number(item.product_id),
      quantity: parseNumber(item.quantity)
    }))
    .filter((item) => item.product_id && item.quantity && item.quantity > 0);

  req.session.cart = cart;
  return cart;
}

async function loadProducts(searchTerm = '', categoryFilter = '', groupFilter = '') {
  let query = `
    SELECT *
    FROM product_catalog_view p
  `;
  const params = [];
  const whereClauses = [];

  if (searchTerm) {
    whereClauses.push(`(
      LOWER(p.product_name) LIKE LOWER(:${params.length + 1})
      OR LOWER(p.category) LIKE LOWER(:${params.length + 2})
      OR LOWER(p.farmer_name) LIKE LOWER(:${params.length + 3})
    )`);
    params.push(`%${searchTerm}%`, `%${searchTerm}%`, `%${searchTerm}%`);
  }

  if (categoryFilter) {
    whereClauses.push(`LOWER(p.category) = LOWER(:${params.length + 1})`);
    params.push(categoryFilter);
  }

  if (groupFilter === 'cereals') {
    whereClauses.push(`(
      LOWER(p.product_name) LIKE LOWER(:${params.length + 1})
      OR LOWER(p.product_name) LIKE LOWER(:${params.length + 2})
      OR LOWER(p.product_name) LIKE LOWER(:${params.length + 3})
      OR LOWER(p.product_name) LIKE LOWER(:${params.length + 4})
    )`);
    params.push('%rice%', '%wheat%', '%bajra%', '%jowar%');
  }

  if (groupFilter === 'pulses') {
    whereClauses.push(`(
      LOWER(p.product_name) LIKE LOWER(:${params.length + 1})
      OR LOWER(p.product_name) LIKE LOWER(:${params.length + 2})
      OR LOWER(p.product_name) LIKE LOWER(:${params.length + 3})
      OR LOWER(p.product_name) LIKE LOWER(:${params.length + 4})
    )`);
    params.push('%dal%', '%moong%', '%urad%', '%gram%');
  }

  if (whereClauses.length) {
    query += ` WHERE ${whereClauses.join(' AND ')}`;
  }

  query += ` ORDER BY p.product_id DESC`;
  const result = await runQuery(query, params);
  return result.rows.map((row) => enrichProduct(toLowerKeys(row)));
}

// ---------------- AUTH ----------------
app.get('/login', (req, res) => res.render('login', { error: null }));

app.post('/login', async (req, res) => {
  const { emailOrPhone, password, type } = req.body;

  try {
    if (type === 'admin') {
      if (emailOrPhone !== ADMIN_CREDENTIALS.username || password !== ADMIN_CREDENTIALS.password) {
        return res.render('login', { error: 'Invalid admin credentials' });
      }

      req.session.user = {
        admin_id: 1,
        name: ADMIN_CREDENTIALS.name,
        username: ADMIN_CREDENTIALS.username
      };
      req.session.userType = 'admin';
      return res.redirect('/admin');
    }

    const query = type === 'farmer'
      ? `SELECT * FROM farmer WHERE phone = :1`
      : `SELECT * FROM customer WHERE email = :1`;

    const result = await runQuery(query, [emailOrPhone]);
    if (result.rows.length === 0) {
      return res.render('login', { error: 'Invalid credentials' });
    }

    const user = toLowerKeys(result.rows[0]);
    if (!user.password_hash) {
      return res.render('login', { error: 'Password missing in DB' });
    }

    const isMatch = user.password_hash.startsWith('$2')
      ? await bcrypt.compare(password, user.password_hash)
      : password === user.password_hash;

    if (!isMatch) {
      return res.render('login', { error: 'Invalid password' });
    }

    req.session.user = user;
    req.session.userType = type;
    sanitizeCart(req);
    res.redirect(type === 'farmer' ? '/farmer/dashboard' : '/');
  } catch {
    res.render('login', { error: 'Login error' });
  }
});

app.get('/register', (req, res) => res.render('register', { error: null }));

app.post('/register', async (req, res) => {
  const { type, name, phone, password, email, address, location, bank_details } = req.body;

  if (!type || !name || !phone || !password) {
    return res.render('register', { error: 'Please fill in all required fields.' });
  }

  try {
    const passwordHash = await bcrypt.hash(password, 10);

    if (type === 'farmer') {
      if (!location || !bank_details) {
        return res.render('register', { error: 'Farmer registration requires location and bank details.' });
      }

      let conn;
      try {
        conn = await pool.getConnection();
        await conn.execute(
          `
            BEGIN
              add_farmer(:name, :phone, :location, :bank_details, :password_hash, :farmer_id);
            END;
          `,
          {
            name,
            phone,
            location,
            bank_details,
            password_hash: passwordHash,
            farmer_id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
          }
        );
        await conn.commit();
      } finally {
        if (conn) await conn.close();
      }
    } else {
      if (!email || !address) {
        return res.render('register', { error: 'Customer registration requires email and address.' });
      }

      let conn;
      try {
        conn = await pool.getConnection();
        await conn.execute(
          `
            BEGIN
              marketplace_pkg.add_customer(:name, :email, :phone, :address, :password_hash, :customer_id);
            END;
          `,
          {
            name,
            email,
            phone,
            address,
            password_hash: passwordHash,
            customer_id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
          }
        );
        await conn.commit();
      } finally {
        if (conn) await conn.close();
      }
    }

    res.redirect('/login');
  } catch (err) {
    const message = err && err.errorNum === 1
      ? 'That email is already registered.'
      : 'Registration failed. Please try again.';
    res.render('register', { error: message });
  }
});

app.get('/logout', (req, res) => {
  req.session.destroy(() => {
    res.redirect('/login');
  });
});

// ---------------- HOME ----------------
app.get('/', async (req, res) => {
  try {
    const selectedCategory = req.query.category || '';
    const selectedGroup = req.query.group || '';
    const products = await loadProducts(req.query.q || '', selectedCategory, selectedGroup);
    res.render('home', {
      products,
      searchQuery: req.query.q || '',
      selectedCategory,
      selectedGroup
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
});

// ---------------- CART ----------------
app.post('/cart/add', async (req, res) => {
  if (req.session.userType !== 'customer') return res.redirect('/login');

  const productId = Number(req.body.product_id);
  const quantity = parseNumber(req.body.quantity);
  const redirectTo = req.body.redirect_to || '/order';

  if (!productId || !quantity || quantity <= 0) {
    return res.redirect(`${redirectTo}?error=${encodeURIComponent('Invalid cart quantity')}`);
  }

  try {
    const products = await fetchProductsByIds([productId]);
    const product = products[0];

    if (!product) {
      return res.redirect(`${redirectTo}?error=${encodeURIComponent('Product not found')}`);
    }
    if (product.is_expired) {
      return res.redirect(`${redirectTo}?error=${encodeURIComponent('Expired products cannot be added to cart')}`);
    }
    if (quantity > Number(product.available_quantity)) {
      return res.redirect(`${redirectTo}?error=${encodeURIComponent('Requested quantity exceeds stock')}`);
    }

    const cart = sanitizeCart(req);
    const existing = cart.find((item) => Number(item.product_id) === productId);
    if (existing) {
      existing.quantity = roundCurrency(existing.quantity + quantity);
    } else {
      cart.push({ product_id: productId, quantity });
    }

    req.session.cart = cart;
    res.redirect(`${redirectTo}?message=${encodeURIComponent('Added to cart')}`);
  } catch (err) {
    res.redirect(`${redirectTo}?error=${encodeURIComponent(err.message)}`);
  }
});

app.post('/cart/update', (req, res) => {
  if (req.session.userType !== 'customer') return res.redirect('/login');

  const productId = Number(req.body.product_id);
  const quantity = parseNumber(req.body.quantity);
  const cart = sanitizeCart(req);

  req.session.cart = cart
    .map((item) => {
      if (Number(item.product_id) !== productId) return item;
      return { ...item, quantity };
    })
    .filter((item) => item.quantity && item.quantity > 0);

  res.redirect('/order');
});

app.post('/cart/remove', (req, res) => {
  if (req.session.userType !== 'customer') return res.redirect('/login');

  const productId = Number(req.body.product_id);
  req.session.cart = sanitizeCart(req).filter((item) => Number(item.product_id) !== productId);
  res.redirect('/order');
});

// ---------------- ORDER PAGE ----------------
app.get('/order', async (req, res) => {
  if (req.session.userType !== 'customer') return res.redirect('/login');

  try {
    const [cartState, ordersResult] = await Promise.all([
      buildCartState(req),
      runQuery(
        `SELECT *
         FROM customer_order_view
         WHERE customer_id = :1
         ORDER BY order_date DESC, order_id DESC`,
        [req.session.user.customer_id]
      )
    ]);

    res.render('order', {
      cartState,
      orders: ordersResult.rows.map(toLowerKeys),
      defaultAddress: req.session.user.address || '',
      message: req.query.message,
      error: req.query.error,
      searchQuery: req.query.q || ''
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
});

app.post('/order/:orderId/cancel', async (req, res) => {
  if (req.session.userType !== 'customer') return res.redirect('/login');

  const orderId = Number(req.params.orderId);
  const cancelReason = (req.body.cancel_reason || '').trim();

  if (!orderId) {
    return res.redirect('/order?error=' + encodeURIComponent('Invalid order'));
  }

  let conn;

  try {
    conn = await pool.getConnection();
    const result = await conn.execute(
      `
        BEGIN
          marketplace_pkg.cancel_customer_order(
            :order_id,
            :customer_id,
            :cancel_reason,
            :refund_percent,
            :refund_amount
          );
        END;
      `,
      {
        order_id: orderId,
        customer_id: req.session.user.customer_id,
        cancel_reason: cancelReason || null,
        refund_percent: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER },
        refund_amount: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      }
    );

    await conn.commit();
    const refundPercent = Number(result.outBinds.refund_percent || 0);
    res.redirect('/order?message=' + encodeURIComponent(`Order cancelled. ${refundPercent}% refund applied.`));
  } catch (err) {
    if (conn) await conn.rollback();
    res.redirect('/order?error=' + encodeURIComponent(err.message));
  } finally {
    if (conn) await conn.close();
  }
});

app.post('/order/:orderId/review', async (req, res) => {
  if (req.session.userType !== 'customer') return res.redirect('/login');

  const orderId = Number(req.params.orderId);
  const productId = Number(req.body.product_id);
  const rating = Number(req.body.rating);
  const reviewText = (req.body.review_text || '').trim();

  if (!orderId || !productId || !Number.isInteger(rating) || rating < 1 || rating > 5) {
    return res.redirect('/order?error=' + encodeURIComponent('Please provide a valid review rating'));
  }

  let conn;

  try {
    conn = await pool.getConnection();
    await conn.execute(
      `
        BEGIN
          marketplace_pkg.save_product_review(
            :order_id,
            :product_id,
            :customer_id,
            :rating,
            :review_text
          );
        END;
      `,
      {
        order_id: orderId,
        product_id: productId,
        customer_id: req.session.user.customer_id,
        rating,
        review_text: reviewText || null
      }
    );

    await conn.commit();
    res.redirect('/order?message=' + encodeURIComponent('Review saved successfully'));
  } catch (err) {
    if (conn) await conn.rollback();
    res.redirect('/order?error=' + encodeURIComponent(err.message));
  } finally {
    if (conn) await conn.close();
  }
});

app.get('/checkout', async (req, res) => {
  if (req.session.userType !== 'customer') return res.redirect('/login');

  try {
    const cartState = await buildCartState(req);
    if (!cartState.items.length) {
      return res.redirect('/order?error=' + encodeURIComponent('Your bag is empty'));
    }

    res.render('checkout', {
      cartState,
      defaultAddress: req.session.user.address || '',
      message: req.query.message,
      error: req.query.error
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
});

// ---------------- CHECKOUT ----------------
app.post('/order/checkout', async (req, res) => {
  if (req.session.userType !== 'customer') return res.redirect('/login');

  const paymentMode = (req.body.payment_mode || '').trim();
  const deliveryAddress = (req.body.delivery_address || '').trim();

  if (!paymentMode || !deliveryAddress) {
    return res.redirect('/order?error=' + encodeURIComponent('Payment mode and delivery address are required'));
  }

  let conn;

  try {
    const cart = sanitizeCart(req);
    if (!cart.length) {
      return res.redirect('/order?error=' + encodeURIComponent('Your cart is empty'));
    }

    conn = await pool.getConnection();
    const cartState = await buildCartState(req, conn);

    if (!cartState.items.length) {
      return res.redirect('/order?error=' + encodeURIComponent('Your cart is empty'));
    }

    const invalidItem = cartState.items.find((item) => item.is_expired || item.has_stock_issue);
    if (invalidItem) {
      const message = invalidItem.is_expired
        ? `${invalidItem.product_name} is expired and cannot be ordered`
        : `${invalidItem.product_name} does not have enough stock`;
      return res.redirect('/order?error=' + encodeURIComponent(message));
    }

    const createdOrders = [];

    for (const item of cartState.items) {
      const orderResult = await conn.execute(
        `
          BEGIN
            place_grouped_order_transaction(
              :customer_id,
              :product_id,
              :quantity,
              :price,
              :original_price,
              :discount_percent,
              :payment_mode,
              :delivery_address,
              :order_id
            );
          END;
        `,
        {
          customer_id: req.session.user.customer_id,
          product_id: item.product_id,
          quantity: item.quantity,
          price: item.discounted_price_per_kg,
          original_price: item.original_price_per_kg,
          discount_percent: item.discount_percent,
          payment_mode: paymentMode,
          delivery_address: deliveryAddress,
          order_id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
        }
      );

      createdOrders.push(orderResult.outBinds.order_id);
    }

    await conn.commit();
    req.session.cart = [];
      res.redirect(`/order?message=${encodeURIComponent(`Placed ${createdOrders.length} order(s) successfully`)}`);
  } catch (err) {
    if (conn) await conn.rollback();
    res.redirect('/order?error=' + encodeURIComponent(err.message));
  } finally {
    if (conn) await conn.close();
  }
});

// ---------------- FARMERS DIRECTORY ----------------
app.get('/farmer', async (req, res) => {
  try {
    const result = await runQuery(
      `SELECT farmer_id, name, phone, location
       FROM farmer
       ORDER BY name`
    );

    res.render('farmer_directory', {
      farmers: result.rows.map(toLowerKeys)
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
});

app.get('/farmer/dashboard', async (req, res) => {
  if (req.session.userType !== 'farmer') return res.redirect('/login');

  try {
    const farmerId = req.session.user.farmer_id;
    const [summaryResult, ordersResult] = await Promise.all([
      runQuery(
        `SELECT
            COUNT(DISTINCT p.product_id) AS total_products,
            COUNT(DISTINCT o.order_id) AS total_orders,
            NVL(SUM(od.quantity), 0) AS total_quantity_sold,
            NVL(SUM(CASE WHEN o.order_status = 'Delivered' THEN od.quantity * od.price ELSE 0 END), 0) AS delivered_revenue,
            NVL(SUM(CASE WHEN o.order_status IN ('Placed', 'Packed', 'Shipped') THEN od.quantity * od.price ELSE 0 END), 0) AS open_order_value
         FROM product p
         LEFT JOIN order_details od ON od.product_id = p.product_id
         LEFT JOIN orders o ON o.order_id = od.order_id
         WHERE p.farmer_id = :1`,
        [farmerId]
      ),
        runQuery(
          `SELECT *
         FROM farmer_order_view
         WHERE farmer_id = :1
         ORDER BY order_date DESC, order_id DESC`,
        [farmerId]
      )
    ]);

    const summary = toLowerKeys(summaryResult.rows[0] || {});

    res.render('farmer_dashboard', {
      summary: {
        total_products: Number(summary.total_products || 0),
        total_orders: Number(summary.total_orders || 0),
        total_quantity_sold: Number(summary.total_quantity_sold || 0),
        delivered_revenue: Number(summary.delivered_revenue || 0),
        open_order_value: Number(summary.open_order_value || 0)
      },
      orders: ordersResult.rows.map(toLowerKeys),
      message: req.query.message,
      error: req.query.error
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
});

app.post('/farmer/order/:orderId/status', async (req, res) => {
  if (req.session.userType !== 'farmer') return res.redirect('/login');

    const orderId = Number(req.params.orderId);
    const status = (req.body.status || '').trim();
    const allowedStatuses = ['Packed', 'Shipped', 'Delivered'];

  if (!orderId || !allowedStatuses.includes(status)) {
    return res.redirect('/farmer/dashboard?error=' + encodeURIComponent('Invalid order status update'));
  }

  try {
      await runQuery(
        `
          BEGIN
            marketplace_pkg.update_farmer_order_status(:order_id, :farmer_id, :status);
          END;
        `,
        {
          order_id: orderId,
          farmer_id: req.session.user.farmer_id,
          status
        },
        { autoCommit: true }
    );

    res.redirect('/farmer/dashboard?message=' + encodeURIComponent(`Order #${orderId} updated to ${status}`));
  } catch (err) {
    res.redirect('/farmer/dashboard?error=' + encodeURIComponent(err.message));
  }
});

// ---------------- CUSTOMERS DIRECTORY ----------------
app.get('/customer', async (req, res) => {
  try {
    const result = await runQuery(
      `SELECT customer_id, name, email, address
       FROM customer
       ORDER BY name`
    );

    res.render('customer_directory', {
      customers: result.rows.map(toLowerKeys)
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
});

// ---------------- ADMIN DASHBOARD ----------------
app.get('/admin', async (req, res) => {
  if (req.session.userType !== 'admin') return res.redirect('/login');

  try {
    const [farmersResult, customersResult, productsResult, ordersResult, revenueResult] = await Promise.all([
      runQuery(
        `SELECT farmer_id, name, phone, location
         FROM farmer
         ORDER BY farmer_id DESC`
      ),
      runQuery(
        `SELECT customer_id, name, email, phone, address
         FROM customer
         ORDER BY customer_id DESC`
      ),
      runQuery(
        `SELECT *
         FROM product_catalog_view
         ORDER BY product_id DESC`
      ),
      runQuery(
          `SELECT *
         FROM admin_order_view
         ORDER BY order_date DESC, order_id DESC`
      ),
      runQuery(
        `SELECT get_total_revenue() AS total_revenue
         FROM dual`
      )
    ]);

    res.render('admin', {
      farmers: farmersResult.rows.map(toLowerKeys),
      customers: customersResult.rows.map(toLowerKeys),
      products: productsResult.rows.map((row) => enrichProduct(toLowerKeys(row))),
      orders: ordersResult.rows.map(toLowerKeys),
      totalRevenue: Number(toLowerKeys(revenueResult.rows[0] || {}).total_revenue || 0),
      message: req.query.message,
      error: req.query.error
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
});

app.post('/admin/farmer/:farmerId/delete', async (req, res) => {
  if (req.session.userType !== 'admin') return res.redirect('/login');

  const farmerId = Number(req.params.farmerId);
  let conn;

  try {
    conn = await pool.getConnection();

    const farmerResult = await conn.execute(
      `SELECT name
       FROM farmer
       WHERE farmer_id = :1`,
      [farmerId]
    );

    if (farmerResult.rows.length === 0) {
      return res.redirect('/admin?error=' + encodeURIComponent('Farmer not found'));
    }

    const productResult = await conn.execute(
      `SELECT product_id
       FROM product
       WHERE farmer_id = :1`,
      [farmerId]
    );
    const productIds = productResult.rows.map((row) => Number(Array.isArray(row) ? row[0] : row.PRODUCT_ID));

    if (productIds.length) {
      const orderResult = await conn.execute(
        `SELECT DISTINCT order_id
         FROM order_details
         WHERE product_id IN (${buildInClause(productIds)})`,
        productIds
      );
      const orderIds = orderResult.rows.map((row) => Number(Array.isArray(row) ? row[0] : row.ORDER_ID));

      if (orderIds.length) {
        await conn.execute(
          `DELETE FROM product_reviews
           WHERE order_id IN (${buildInClause(orderIds)})`,
          orderIds
        );

        await conn.execute(
          `DELETE FROM payment
           WHERE order_id IN (${buildInClause(orderIds)})`,
          orderIds
        );
      }

      await conn.execute(
        `DELETE FROM order_details
         WHERE product_id IN (${buildInClause(productIds)})`,
        productIds
      );

      if (orderIds.length) {
        await conn.execute(
          `DELETE FROM orders
           WHERE order_id IN (${buildInClause(orderIds)})`,
          orderIds
        );
      }
    }

    await conn.execute(
      `DELETE FROM product
       WHERE farmer_id = :1`,
      [farmerId]
    );

    await conn.execute(
      `DELETE FROM farmer
       WHERE farmer_id = :1`,
      [farmerId]
    );

    await conn.commit();
    res.redirect('/admin?message=' + encodeURIComponent('Farmer deleted successfully'));
  } catch (err) {
    if (conn) await conn.rollback();
    res.redirect('/admin?error=' + encodeURIComponent(err.message));
  } finally {
    if (conn) await conn.close();
  }
});

app.post('/admin/customer/:customerId/delete', async (req, res) => {
  if (req.session.userType !== 'admin') return res.redirect('/login');

  const customerId = Number(req.params.customerId);
  let conn;

  try {
    conn = await pool.getConnection();

    const customerResult = await conn.execute(
      `SELECT name
       FROM customer
       WHERE customer_id = :1`,
      [customerId]
    );

    if (customerResult.rows.length === 0) {
      return res.redirect('/admin?error=' + encodeURIComponent('Customer not found'));
    }

    await conn.execute(
      `DELETE FROM product_reviews
       WHERE order_id IN (
         SELECT order_id
         FROM orders
         WHERE customer_id = :1
       )`,
      [customerId]
    );

    await conn.execute(
      `DELETE FROM payment
       WHERE order_id IN (
         SELECT order_id
         FROM orders
         WHERE customer_id = :1
       )`,
      [customerId]
    );

    await conn.execute(
      `DELETE FROM order_details
       WHERE order_id IN (
         SELECT order_id
         FROM orders
         WHERE customer_id = :1
       )`,
      [customerId]
    );

    await conn.execute(
      `DELETE FROM orders
       WHERE customer_id = :1`,
      [customerId]
    );

    await conn.execute(
      `DELETE FROM customer
       WHERE customer_id = :1`,
      [customerId]
    );

    await conn.commit();
    res.redirect('/admin?message=' + encodeURIComponent('Customer deleted successfully'));
  } catch (err) {
    if (conn) await conn.rollback();
    res.redirect('/admin?error=' + encodeURIComponent(err.message));
  } finally {
    if (conn) await conn.close();
  }
});

// ---------------- PRODUCT MANAGEMENT ----------------
app.get('/product', async (req, res) => {
  if (req.session.userType !== 'farmer') return res.redirect('/login');

  try {
    const result = await runQuery(
       `SELECT *
        FROM product_catalog_view
        WHERE farmer_id = :1
        ORDER BY product_id DESC`,
      [req.session.user.farmer_id]
    );

    res.render('product', {
      products: result.rows.map((row) => enrichProduct(toLowerKeys(row))),
      message: req.query.message,
      error: req.query.error
    });
  } catch (err) {
    res.status(500).send(err.message);
  }
});

app.get('/product/:productId/edit', async (req, res) => {
  if (req.session.userType !== 'farmer') return res.redirect('/login');

  try {
    const result = await runQuery(
      `SELECT *
       FROM product_catalog_view
       WHERE product_id = :1
         AND farmer_id = :2`,
      [Number(req.params.productId), req.session.user.farmer_id]
    );

    if (!result.rows.length) {
      return res.redirect('/product?error=' + encodeURIComponent('Product not found'));
    }

    res.render('product_edit', {
      product: enrichProduct(toLowerKeys(result.rows[0])),
      message: req.query.message,
      error: req.query.error
    });
  } catch (err) {
    res.redirect('/product?error=' + encodeURIComponent(err.message));
  }
});

app.post('/product', upload.single('image'), async (req, res) => {
  if (req.session.userType !== 'farmer') return res.redirect('/login');

  const {
    product_name,
    category,
    price_per_kg,
    available_quantity,
    expiry_date,
    manual_discount_percent
  } = req.body;

  const parsedPrice = parseNumber(price_per_kg);
  const parsedQuantity = parseNumber(available_quantity);
  const parsedManualDiscount = Math.max(0, Math.min(80, parseNumber(manual_discount_percent || 0) || 0));
  const parsedExpiryDate = expiry_date ? new Date(`${expiry_date}T00:00:00`) : null;

  if (!product_name || !category || !parsedPrice || !parsedQuantity || !expiry_date || Number.isNaN(parsedExpiryDate.getTime())) {
    return res.redirect('/product?error=' + encodeURIComponent('Missing or invalid product details'));
  }

  try {
    await runQuery(
      `
        BEGIN
          marketplace_pkg.add_product(
            :farmer_id,
            :product_name,
            :category,
            :price_per_kg,
            :available_quantity,
            :image_url,
            :expiry_date,
            :manual_discount_percent,
            :product_id
          );
        END;
      `,
      {
        farmer_id: req.session.user.farmer_id,
        product_name,
        category,
        price_per_kg: parsedPrice,
        available_quantity: parsedQuantity,
        image_url: req.file ? req.file.filename : null,
        expiry_date: parsedExpiryDate,
        manual_discount_percent: parsedManualDiscount,
        product_id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      },
      { autoCommit: true }
    );

    res.redirect('/product?message=' + encodeURIComponent('Product added successfully'));
  } catch (err) {
    res.redirect('/product?error=' + encodeURIComponent(err.message));
  }
});

app.post('/product/:productId/edit', upload.single('image'), async (req, res) => {
  if (req.session.userType !== 'farmer') return res.redirect('/login');

  const productId = Number(req.params.productId);
  const {
    product_name,
    category,
    price_per_kg,
    available_quantity,
    expiry_date,
    manual_discount_percent
  } = req.body;

  const parsedPrice = parseNumber(price_per_kg);
  const parsedQuantity = parseNumber(available_quantity);
  const parsedManualDiscount = Math.max(0, Math.min(80, parseNumber(manual_discount_percent || 0) || 0));
  const parsedExpiryDate = expiry_date ? new Date(`${expiry_date}T00:00:00`) : null;

  if (!productId || !product_name || !category || !parsedPrice || !parsedQuantity || !expiry_date || Number.isNaN(parsedExpiryDate.getTime())) {
    return res.redirect(`/product/${productId}/edit?error=${encodeURIComponent('Missing or invalid product details')}`);
  }

  try {
    const existingResult = await runQuery(
      `SELECT image_url
       FROM product_catalog_view
       WHERE product_id = :1
         AND farmer_id = :2`,
      [productId, req.session.user.farmer_id]
    );

    if (!existingResult.rows.length) {
      return res.redirect('/product?error=' + encodeURIComponent('Product not found'));
    }

    const existing = toLowerKeys(existingResult.rows[0]);

    await runQuery(
      `
        BEGIN
          marketplace_pkg.update_product(
            :product_id,
            :farmer_id,
            :product_name,
            :category,
            :price_per_kg,
            :available_quantity,
            :expiry_date,
            :manual_discount_percent,
            :image_url
          );
        END;
      `,
      {
        product_id: productId,
        farmer_id: req.session.user.farmer_id,
        product_name,
        category,
        price_per_kg: parsedPrice,
        available_quantity: parsedQuantity,
        expiry_date: parsedExpiryDate,
        manual_discount_percent: parsedManualDiscount,
        image_url: req.file ? req.file.filename : existing.image_url
      },
      { autoCommit: true }
    );

    res.redirect('/product?message=' + encodeURIComponent('Product updated successfully'));
  } catch (err) {
    res.redirect(`/product/${productId}/edit?error=${encodeURIComponent(err.message)}`);
  }
});

app.post('/product/:productId/delete', async (req, res) => {
  if (req.session.userType !== 'farmer') return res.redirect('/login');

  const productId = Number(req.params.productId);
  try {
    await runQuery(
      `
        BEGIN
          marketplace_pkg.delete_product_if_unused(:product_id, :farmer_id);
        END;
      `,
      {
        product_id: productId,
        farmer_id: req.session.user.farmer_id
      },
      { autoCommit: true }
    );

    res.redirect('/product?message=' + encodeURIComponent('Product deleted successfully'));
  } catch (err) {
    res.redirect('/product?error=' + encodeURIComponent(err.message));
  }
});

// ---------------- SERVER ----------------
const port = process.env.PORT || 3005;
app.listen(port, () => console.log(`Server running on port ${port}`));
