DECLARE
  v_count INT;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'C##FARMER';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP USER C##FARMER CASCADE';
  END IF;
END;
/
CREATE USER C##FARMER IDENTIFIED BY farmer123;
GRANT CONNECT, RESOURCE, DBA TO C##FARMER;
ALTER USER C##FARMER DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CONNECT C##FARMER/farmer123;

CREATE TABLE farmer (
    farmer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    phone VARCHAR2(20),
    location VARCHAR2(255),
    bank_details VARCHAR2(255),
    password_hash VARCHAR2(255) NOT NULL
);

CREATE TABLE customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE,
    phone VARCHAR2(20),
    address VARCHAR2(255),
    password_hash VARCHAR2(255) NOT NULL
);

CREATE TABLE product (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id NUMBER NOT NULL REFERENCES farmer(farmer_id),
    product_name VARCHAR2(255) NOT NULL,
    category VARCHAR2(50) CHECK (category IN ('Vegetable', 'Fruit', 'Grain')) NOT NULL,
    price_per_kg NUMBER(10,2) NOT NULL CHECK (price_per_kg >= 0),
    available_quantity NUMBER(10,2) NOT NULL CHECK (available_quantity >= 0),
    image_url VARCHAR2(255),
    expiry_date DATE NOT NULL
);

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL REFERENCES customer(customer_id),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total_amount NUMBER(10,2) NOT NULL,
    order_status VARCHAR2(50) DEFAULT 'Placed' NOT NULL,
    delivery_address VARCHAR2(255),
    tracking_location VARCHAR2(255),
    tracking_status VARCHAR2(100) DEFAULT 'Processing'
);

CREATE TABLE order_details (
    order_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL REFERENCES orders(order_id),
    product_id NUMBER NOT NULL REFERENCES product(product_id),
    quantity NUMBER(10,2) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    original_price NUMBER(10,2) NOT NULL,
    discount_percent NUMBER(5,2) DEFAULT 0 NOT NULL
);

CREATE TABLE payment (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL REFERENCES orders(order_id),
    payment_mode VARCHAR2(50) NOT NULL,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    payment_status VARCHAR2(50) NOT NULL
);

CREATE OR REPLACE TRIGGER trg_prevent_negative_price
BEFORE INSERT OR UPDATE ON product
FOR EACH ROW
BEGIN
    IF :NEW.price_per_kg <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Price per kg must be greater than zero.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_update_stock_after_order
AFTER INSERT ON order_details
FOR EACH ROW
BEGIN
    UPDATE product
    SET available_quantity = available_quantity - :NEW.quantity
    WHERE product_id = :NEW.product_id;
END;
/

CREATE OR REPLACE PROCEDURE place_grouped_order_transaction (
    p_customer_id IN NUMBER,
    p_product_id IN NUMBER,
    p_quantity IN NUMBER,
    p_price IN NUMBER,
    p_original_price IN NUMBER,
    p_discount_percent IN NUMBER,
    p_payment_mode IN VARCHAR2
)
IS
    v_total NUMBER(10,2);
    v_order_id NUMBER;
BEGIN
    v_total := p_price * p_quantity;

    INSERT INTO orders (customer_id, total_amount, order_status)
    VALUES (p_customer_id, v_total, 'Placed')
    RETURNING order_id INTO v_order_id;

    INSERT INTO order_details (order_id, product_id, quantity, price, original_price, discount_percent)
    VALUES (v_order_id, p_product_id, p_quantity, p_price, p_original_price, p_discount_percent);

    INSERT INTO payment (order_id, payment_mode, payment_status)
    VALUES (v_order_id, p_payment_mode, 'Success');

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- Fallback passwords are "password123" for testing.
INSERT INTO farmer (name, phone, location, bank_details, password_hash) VALUES ('Rajesh Kumar', '9876543210', 'Pune, Maharashtra', 'SBI 123456789', 'password123');
INSERT INTO farmer (name, phone, location, bank_details, password_hash) VALUES ('Anita Patel', '8765432109', 'Nashik, Maharashtra', 'HDFC 987654321', 'password123');
INSERT INTO farmer (name, phone, location, bank_details, password_hash) VALUES ('Suresh Singh', '7654321098', 'Ludhiana, Punjab', 'ICICI 456123789', 'password123');

INSERT INTO customer (name, email, phone, address, password_hash) VALUES ('Arun Nair', 'arun.nair@example.com', '9988776655', 'Kochi, Kerala', 'password123');
INSERT INTO customer (name, email, phone, address, password_hash) VALUES ('Meera Joseph', 'meera.joseph@example.com', '8877665544', 'Kottayam, Kerala', 'password123');

INSERT INTO product (farmer_id, product_name, category, price_per_kg, available_quantity, expiry_date) VALUES (1, 'Onions', 'Vegetable', 40.0, 500.0, TRUNC(SYSDATE) + 10);
INSERT INTO product (farmer_id, product_name, category, price_per_kg, available_quantity, expiry_date) VALUES (1, 'Tomatoes', 'Vegetable', 30.0, 200.0, TRUNC(SYSDATE) + 2);
INSERT INTO product (farmer_id, product_name, category, price_per_kg, available_quantity, expiry_date) VALUES (2, 'Grapes', 'Fruit', 80.0, 150.0, TRUNC(SYSDATE) + 1);
INSERT INTO product (farmer_id, product_name, category, price_per_kg, available_quantity, expiry_date) VALUES (3, 'Wheat (Lokwan)', 'Grain', 35.0, 1000.0, TRUNC(SYSDATE) + 60);
INSERT INTO product (farmer_id, product_name, category, price_per_kg, available_quantity, expiry_date) VALUES (3, 'Rice (Basmati)', 'Grain', 90.0, 400.0, TRUNC(SYSDATE) + 45);

COMMIT;
EXIT;
